[versions]
# plugins
kotlin = "2.2.10"
androidGradlePlugin = "8.13.0"
# ksp のバージョンは、kotlin_version と同じ世代のものを指定する必要がある。
# https://github.com/google/ksp/releases で確認する。
ksp = "2.2.10-2.0.2"

# libraries
coreKtx = "1.17.0"
appcompat = "1.7.1"
constraintLayout = "2.2.1"
material = "1.13.0"
okhttp = "5.1.0"
coroutinesCore = "1.10.2"
coroutinesAndroid = "1.10.2"
lifecycleExtensions = "2.2.0"
lifecycleViewModelKtx = "2.9.3"
lifecycleRuntimeKtx = "2.9.3"
lifecycleLiveDataKtx = "2.9.3"
media3Exoplayer = "1.8.0"
media3Ui = "1.8.0"
junit = "4.13.2"
androidxTestExtJunit = "1.3.0"
espressoCore = "3.7.0"
androidUtilities = "4.7.1"
androidBinding = "1.9.11"
androidDialog = "6.1.0"
androidViewEx = "1.1.19"
androidMediaPlayer = "3.3.2"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
roomRuntime = "2.8.0"
activity = "1.11.0"

[libraries]
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Exoplayer" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-coroutines = { group = "com.squareup.okhttp3", name = "okhttp-coroutines", version.ref = "okhttp" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesCore" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesAndroid" }
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycleExtensions" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewModelKtx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLiveDataKtx" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Ui" }
android-utilities = { group = "com.github.toyota-m2k", name = "android-utilities", version.ref = "androidUtilities" }
android-binding = { group = "com.github.toyota-m2k", name = "android-binding", version.ref = "androidBinding" }
android-dialog = { group = "com.github.toyota-m2k", name = "android-dialog", version.ref = "androidDialog" }
android-viewex = { group = "com.github.toyota-m2k", name = "android-viewex", version.ref = "androidViewEx" }
android-media-player = { group = "com.github.toyota-m2k", name="android-media-player", version.ref = "androidMediaPlayer" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }